name: Build and Compile CMake C++ Project

on:
  push:
    branches:
      - actions  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libncurses5-dev

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Archive Artifacts
        run: |
          cd build/src
          mkdir -p artifacts
          mv TextDungeon artifacts/
          tar -czvf TextDungeon.tar.gz artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/src/TextDungeon.tar.gz