name: Build and Compile CMake C++ Project

on:
  push:
    branches:
      - actions  # Change this to your main branch name

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libncurses5-dev

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Archive Artifacts
        run: |
          cd build/src
          mkdir -p artifacts
          mv TextDungeon artifacts/
          tar -czvf TextDungeon.tar.gz artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-build-artifacts
          path: build/src/TextDungeon.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1

      - name: Install CMake
        run: |
          choco install -y cmake

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg integrate install

      - name: Install and Build Curses Library
        run: |
          vcpkg install ncurses
          vcpkg export --output=C:/libs/ncurses

      - name: Configure and Build
        run: |
          mkdir build
          cd build
            
          cmake -DCMAKE_PREFIX_PATH="C:/libs/ncurses" ..
            
          # Build the project
          cmake --build . --config Release

      - name: Archive Artifacts
        run: |
          cd build/src/Release
          mkdir -p artifacts
          mv TextDungeon.exe artifacts/
          tar -czvf TextDungeon-windows.tar.gz artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-build-artifacts
          path: build/src/Release/TextDungeon-windows.tar.gz

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          brew update
          brew install cmake ncurses

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Archive Artifacts
        run: |
          cd build/src
          mkdir -p artifacts
          mv TextDungeon artifacts/
          tar -czvf TextDungeon-macos.tar.gz artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-build-artifacts
          path: build/src/TextDungeon-macos.tar.gz
