name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get -yq update
            sudo apt-get -yq install cmake g++
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install cmake
          fi

      - name: Build on ${{ matrix.os }}
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .