name: Build and Test

on:
  push:
    branches:
      - master

obs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: 3.21.0  # Adjust the CMake version as needed

      - name: Create build directory
        run: mkdir build
        working-directory: ${{ github.workspace }}

      - name: Configure and build
        run: |
          cd build
          cmake ..
          cmake --build .
        working-directory: ${{ github.workspace }}

      - name: Capture CMake files
        uses: actions/upload-artifact@v2
        with:
          name: cmake-files
          path: build/CMakeFiles